server:
  port: 8200

api:
  yahooFc:
    #host: "localhost:8100"
    host: "pkproject.onrender.com"
    endpoints:
      markets: "/api/no2/getMarketData"
      ohmarkets: "/api/no2/getMarketOHData"
      search: "/api/no2/search"
      checkAllSybmol: "/api/no2/checkAllSybmol"
      checkAllSybmolName: "/api/no2/checkAllSybmolName"
      
